UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Add_email.bmp, Script\Add_email.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Add_email_alt.bmp, Script\Add_email_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Add_email_alternative.bmp, Script\Add_email_alternative.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Add_email_neon.bmp, Script\Add_email_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Add_email_neon_alt.bmp, Script\Add_email_neon_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Amazon_bitch.bmp, Script\Amazon_bitch.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Amazon_bitch2.bmp, Script\Amazon_bitch2.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Amazon_otp_Byom.bmp, Script\Amazon_otp_Byom.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Amazon_otp_Byom2.bmp, Script\Amazon_otp_Byom2.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Amazon_otp_Byom2_alt.bmp, Script\Amazon_otp_Byom2_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Byom_refresh.bmp, Script\Byom_refresh.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Byom_refresh_alt.bmp, Script\Byom_refresh_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Change.bmp, Script\Change.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Change_alt.bmp, Script\Change_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Close.bmp, Script\Close.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Cloudflare.bmp, Script\Cloudflare.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Cloudflare_on.bmp, Script\Cloudflare_on.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Cloudflare_switch.bmp, Script\Cloudflare_switch.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Confirm_1.bmp, Script\Confirm_1.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Create_Your_account.bmp, Script\Create_Your_account.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Create_Your_account_alt.bmp, Script\Create_Your_account_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Create_Your_account_neon.bmp, Script\Create_Your_account_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Create_Your_account_neon_alt.bmp, Script\Create_Your_account_neon_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/EName.bmp, Script\EName.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/EPass.bmp, Script\EPass.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/EPass_alt.bmp, Script\EPass_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/End.bmp, Script\End.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/End_alt.bmp, Script\End_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Link.bmp, Script\Link.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Mail_Byom.bmp, Script\Mail_Byom.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Mail_Name.bmp, Script\Mail_Name.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_delete.bmp, Script\Number_delete.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal.bmp, Script\Number_removal.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal_2.bmp, Script\Number_removal_2.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal_3.bmp, Script\Number_removal_3.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal_3_neon.bmp, Script\Number_removal_3_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal_alt.bmp, Script\Number_removal_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal_altt.bmp, Script\Number_removal_altt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Number_removal_neon.bmp, Script\Number_removal_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/Password.bmp, Script\Password.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/amazon_japan.bmp, Script\amazon_japan.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/error.bmp, Script\error.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/error_alt.bmp, Script\error_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/number_delete_1.bmp, Script\number_delete_1.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/otp_error.bmp, Script\otp_error.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/otp_error_byom.bmp, Script\otp_error_byom.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/pass_error1.bmp, Script\pass_error1.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/raw/main/Images/resend_otp.bmp, Script\resend_otp.bmp
exitapp
return
