UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Add_email.bmp, Add_email.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Add_email_alt.bmp, Add_email_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Add_email_alternative.bmp, Add_email_alternative.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Add_email_neon.bmp, Add_email_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Add_email_neon_alt.bmp, Add_email_neon_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Amazon_bitch.bmp, Amazon_bitch.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Amazon_bitch2.bmp, Amazon_bitch2.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Amazon_otp_Byom.bmp, Amazon_otp_Byom.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Amazon_otp_Byom2.bmp, Amazon_otp_Byom2.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Amazon_otp_Byom2_alt.bmp, Amazon_otp_Byom2_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Byom_refresh.bmp, Byom_refresh.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Byom_refresh_alt.bmp, Byom_refresh_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Change.bmp, Change.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Change_alt.bmp, Change_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Close.bmp, Close.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Cloudflare.bmp, Cloudflare.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Cloudflare_on.bmp, Cloudflare_on.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Cloudflare_switch.bmp, Cloudflare_switch.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Confirm_1.bmp, Confirm_1.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Create_Your_account.bmp, Create_Your_account.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Create_Your_account_alt.bmp, Create_Your_account_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Create_Your_account_neon.bmp, Create_Your_account_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Create_Your_account_neon_alt.bmp, Create_Your_account_neon_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/EName.bmp, EName.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/EPass.bmp, EPass.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/EPass_alt.bmp, EPass_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/End.bmp, End.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/End_alt.bmp, End_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Link.bmp, Link.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Mail_Byom.bmp, Mail_Byom.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Mail_Name.bmp, Mail_Name.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_delete.bmp, Number_delete.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal.bmp, Number_removal.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal_2.bmp, Number_removal_2.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal_3.bmp, Number_removal_3.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal_3_neon.bmp, Number_removal_3_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal_alt.bmp, Number_removal_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal_altt.bmp, Number_removal_altt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Number_removal_neon.bmp, Number_removal_neon.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/Password.bmp, Password.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/amazon_japan.bmp, amazon_japan.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/error.bmp, error.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/error_alt.bmp, error_alt.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/number_delete_1.bmp, number_delete_1.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/otp_error.bmp, otp_error.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/otp_error_byom.bmp, otp_error_byom.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/pass_error1.bmp, pass_error1.bmp
UrlDownloadToFile, https://github.com/philobater/ahk-test/blob/main/Images/resend_otp.bmp, resend_otp.bmp
exitapp
return